name: Docker Image CI

on:
  push:
    branches: '**'
env:
  ECR_REPO_NAME: "ai-repo"
jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Extract branch name
      id: extract_branch
      run: |
        echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION }}
        role-to-assume: arn:aws:iam::905418352696:role/GithubAccess

    - name: Login to shared Amazon ECR
      run: |
           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 763104351884.dkr.ecr.us-east-1.amazonaws.com
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Free up Disk Space
      run: |
            # Remove specific Docker images that are no longer needed
            docker rmi $(docker images -f "dangling=true" -q) || true
            
            # Prune unused Docker objects (images, containers, volumes, and networks)
            docker system prune -f || true

            # Clean up specific directories known to consume a lot of space
            #sudo rm -rf /path/to/large/directory

            # Show disk space usage
            df -h

      
    - name: Build Docker image
      run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ env.BRANCH_NAME }}.${{env.SHA_SHORT}} .

    - name: Run test script
      id: run_test
      run: |
          bash test.sh  ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ env.BRANCH_NAME }}.${{env.SHA_SHORT}}


    - name: Push Docker image to Amazon ECR
      run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ env.BRANCH_NAME }}.${{env.SHA_SHORT}}
